// Generated by components discovery
declare module 'vue' {
  export interface GlobalComponents {
    'OrderButton': typeof import('../components/OrderButton.vue')['default'],
    'Overview': typeof import('../components/Overview.vue')['default'],
    'Products': typeof import('../components/Products.vue')['default'],
    'NuxtWelcome': typeof import('../node_modules/nuxt3/dist/app/components/nuxt-welcome.vue')['default'],
    'ClientOnly': typeof import('../node_modules/nuxt3/dist/app/components/client-only')['default']
  }
}
export {}
